// Regenerates board.json from the screen registry. Run: node tools/build_board.js
// Loads the screen files against a stub App (no DOM) and records each defineScreen / defineOverlay call.
const fs = require("fs"), path = require("path"), vm = require("vm");
const root = path.join(__dirname, "..");
const items = [];
const noop = () => {};
const loose = () => new Proxy(function () {}, { get: (t, k) => (k === "then" ? undefined : loose()), apply: () => loose() });
const App = new Proxy({ screens: {}, overlays: {}, order: [], h: loose(), defineScreen: (d) => items.push({ kind: "screen", d }), defineOverlay: (d) => items.push({ kind: "overlay", d }) }, {
  get: (t, k) => (k in t ? t[k] : loose()),
});
const win = { App, DB: null, RAGI: null, addEventListener: noop };
win.window = win;
const ctx = vm.createContext(Object.assign(win, { document: { addEventListener: noop, querySelector: noop, querySelectorAll: () => [] }, console, setTimeout, clearTimeout, module: undefined, location: { search: "" }, history: {} }));
const run = (f) => vm.runInContext(fs.readFileSync(f, "utf8"), ctx, { filename: f });
run(path.join(root, "../../02_Design_System/reference/logic.js"));
run(path.join(root, "data.js"));
const files = ["auth", "student", "editor", "overlays", "compare", "report", "global"];
const fileOf = {};
for (const f of files) { const before = items.length; run(path.join(root, "screens", f + ".js")); for (let i = before; i < items.length; i++) fileOf[items[i].d.id] = "screens/" + f + ".js"; }
const role = () => "both"; // one experience for everyone (D-023)
const num = (id) => (id[0] === "S" ? 0 : 1000) + Number(id.slice(1));
const out = items.map(({ kind, d }) => ({
  id: d.id, name: d.name, kind, group: d.group, role: role(), stories: d.stories || [],
  states: kind === "overlay" ? (d.variants || []).map((v) => v[0]) : (d.states || [["auto"]]).map((s) => s[0]),
  cr: d.tag || null, status: "review", round: 1, file: fileOf[d.id],
})).sort((a, b) => num(a.id) - num(b.id));
const prev = fs.existsSync(path.join(root, "board.json")) ? JSON.parse(fs.readFileSync(path.join(root, "board.json"), "utf8")) : null;
if (prev) for (const o of out) { const p = prev.items.find((x) => x.id === o.id); if (p) { o.status = p.status; o.round = p.round; } }
fs.writeFileSync(path.join(root, "board.json"), JSON.stringify({ $comment: "Generated by tools/build_board.js from the prototype registry. status: todo, wip, review, approved. kind=overlay means it opens as a sheet or dialog in code (S9 is a screen on the PRD list).", items: out }, null, 1) + "\n");
console.log(out.length + " entries: " + out.filter((x) => x.kind === "screen").length + " screens, " + out.filter((x) => x.kind === "overlay").length + " overlays");
