#!/usr/bin/env python3
"""Generate tokens.css and icons.js from tokens.json and icons/*.svg, and verify contrast.

Run from anywhere:  python3 build_assets.py
Exit code 1 if a required contrast pair fails, so it can gate stage 2.
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
T = json.loads((HERE / "tokens.json").read_text())


def lum(hex_):
    h = hex_.lstrip("#")
    c = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    c = [x / 12.92 if x <= 0.03928 else ((x + 0.055) / 1.055) ** 2.4 for x in c]
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def ratio(a, b):
    hi, lo = sorted([lum(a), lum(b)], reverse=True)
    return (hi + 0.05) / (lo + 0.05)


# ---- contrast gate ---------------------------------------------------------
C = {k: v["value"] for k, v in T["color"].items()}
PAIRS = [  # (foreground, background, minimum, why)
    ("ink", "surface", 4.5, "primary text on cards"),
    ("ink", "page", 4.5, "primary text on page"),
    ("ink", "gold", 4.5, "text on gold fills"),
    ("gold", "ink", 4.5, "gold wordmark on ink"),
    ("on-ink", "ink", 4.5, "primary button label"),
    ("body", "surface", 4.5, "secondary text on cards"),
    ("body", "page", 4.5, "secondary text on page"),
    ("muted", "surface", 4.5, "captions on cards"),
    ("muted", "page", 4.5, "captions on page"),
    ("gold-deep", "surface", 4.5, "gold-family text on cards"),
    ("gold-deep", "gold-tint", 4.5, "gold-family text on tint"),
    ("gold-deep", "page", 4.5, "gold-family text on page"),
    ("ink", "gold-tint", 4.5, "text on tint"),
    ("berhasil-ink", "berhasil-fill", 4.5, "Berhasil badge"),
    ("gagal-ink", "gagal-fill", 4.5, "Gagal badge"),
    ("belum-ink", "belum-fill", 4.5, "Belum dinilai badge"),
    ("gagal-ink", "surface", 4.5, "error text on cards"),
    ("line-strong", "surface", 3.0, "input borders on cards (non-text)"),
    ("line-strong", "page", 3.0, "input borders on page (non-text)"),
    ("gold-deep", "surface", 3.0, "icons"),
    ("ink", "berhasil-fill", 4.5, "text next to badges"),
]
failed = 0
report = []
for fg, bg, mn, why in PAIRS:
    r = ratio(C[fg], C[bg])
    ok = r >= mn
    failed += not ok
    report.append(f"| {fg} on {bg} | {r:.2f}:1 | {mn}:1 | {'pass' if ok else 'FAIL'} | {why} |")
(HERE / "contrast-report.md").write_text(
    "# contrast-report.md\n\nGenerated by `build_assets.py` from `tokens.json`. Do not edit by hand.\n\n"
    "| Pair | Ratio | Needs | Result | Use |\n|---|---|---|---|---|\n" + "\n".join(report) + "\n"
)

# ---- tokens.css ------------------------------------------------------------
L = ["/* GENERATED from tokens.json by build_assets.py. Do not edit by hand. */"]
fonts = [
    ("IBM Plex Sans", 400, "normal", "ibm-plex-sans-latin-400-normal"),
    ("IBM Plex Sans", 500, "normal", "ibm-plex-sans-latin-500-normal"),
    ("IBM Plex Sans", 600, "normal", "ibm-plex-sans-latin-600-normal"),
    ("IBM Plex Sans", 700, "normal", "ibm-plex-sans-latin-700-normal"),
    ("Vollkorn", 400, "normal", "vollkorn-latin-400-normal"),
    ("Vollkorn", 400, "italic", "vollkorn-latin-400-italic"),
    ("Vollkorn", 600, "normal", "vollkorn-latin-600-normal"),
    ("Vollkorn", 700, "normal", "vollkorn-latin-700-normal"),
]
for fam, w, st, f in fonts:
    L.append(
        f"@font-face {{ font-family: '{fam}'; font-style: {st}; font-weight: {w}; font-display: swap; "
        f"src: url('fonts/{f}.woff2') format('woff2'); }}"
    )
L.append("\n:root {")
L.append("  --ts: 1; /* text scale: 1 or 1.3 (the 130 % toggle) */")
for k, v in T["color"].items():
    L.append(f"  --c-{k}: {v['value']};")
for k, v in T["font"].items():
    L.append(f"  --font-{k}: {v['value']};")
for k, v in T["type"].items():
    fam = f"var(--font-{v['family']})"
    L.append(f"  --t-{k}-family: {fam};")
    L.append(f"  --t-{k}-weight: {v['weight']};")
    L.append(f"  --t-{k}-size: calc({v['size']}px * var(--ts));")
    L.append(f"  --t-{k}-line: calc({v['line']}px * var(--ts));")
    L.append(f"  --t-{k}-tracking: {v['tracking']};")
for k, v in T["space"].items():
    L.append(f"  --s-{k}: {v}px;")
for k, v in T["radius"].items():
    L.append(f"  --r-{k}: {v}px;")
for k, v in T["size"].items():
    L.append(f"  --z-{k}: {v}px;")
for k, v in T["elevation"].items():
    L.append(f"  --shadow-{k}: {v};")
for k, v in T["motion"].items():
    if isinstance(v, dict):
        L.append(f"  --m-{k}: {v['value']};")
L.append("}")
L.append("@media (prefers-reduced-motion: reduce) { :root { --m-fast: 1ms; --m-base: 1ms; --m-slow: 1ms; --m-spring: linear; } }")
L.append("")
for k, v in T["type"].items():
    extra = ""
    if v.get("transform"):
        extra += f" text-transform: {v['transform']};"
    if v.get("tabular"):
        extra += " font-variant-numeric: tabular-nums lining-nums;"
    L.append(
        f".t-{k} {{ font-family: var(--t-{k}-family); font-weight: var(--t-{k}-weight); "
        f"font-size: var(--t-{k}-size); line-height: var(--t-{k}-line); letter-spacing: var(--t-{k}-tracking);{extra} }}"
    )
(HERE / "tokens.css").write_text("\n".join(L) + "\n")

# ---- icons.js (sprite injected at load, works from file://) ------------------
symbols = []
names = []
for p in sorted((HERE / "icons").glob("*.svg")):
    txt = p.read_text()
    inner = re.search(r"<svg[^>]*>(.*)</svg>", txt, re.S).group(1)
    inner = re.sub(r"\s+", " ", inner).strip()
    symbols.append(f'<symbol id="i-{p.stem}" viewBox="0 0 24 24">{inner}</symbol>')
    names.append(p.stem)
sprite = '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">' + "".join(symbols) + "</svg>"
js = (
    "/* GENERATED by build_assets.py from icons/*.svg (Lucide, ISC licence). Do not edit by hand.\n"
    "   Usage: <svg class=\"icon\" aria-hidden=\"true\"><use href=\"#i-star\"/></svg> */\n"
    "(function(){var s=" + json.dumps(sprite) + ";\n"
    "function add(){var d=document.createElement('div');d.innerHTML=s;document.body.insertBefore(d.firstChild,document.body.firstChild);}\n"
    "if(document.body)add();else document.addEventListener('DOMContentLoaded',add);})();\n"
)
(HERE / "icons.js").write_text(js)

print(f"tokens.css written; icons.js written ({len(names)} icons); contrast: {len(PAIRS) - failed}/{len(PAIRS)} pass")
for line in report:
    if "FAIL" in line:
        print(line)
sys.exit(1 if failed else 0)
